version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: x-bank-v2
    environment:
      POSTGRES_DB: x-bank-v2
      POSTGRES_USER: x-bank-v2
      POSTGRES_PASSWORD: xbankv2
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local